# Rosé Pine
gui:
  nerdFontsVersion: "3"
  border: rounded
  showIcons: true
  theme:
    activeBorderColor:
      - "#31748f"
      - bold
    inactiveBorderColor:
      - "#6e6a86"
    searchingActiveBorderColor:
      - "#f6c177"
    optionsTextColor:
      - "#31748f"
    selectedLineBgColor:
      - "#26233a"
    inactiveViewSelectedLineBgColor:
      - "#403d52"
    cherryPickedCommitFgColor:
      - "#31748f"
    cherryPickedCommitBgColor:
      - "#403d52"
    markedBaseCommitFgColor:
      - "#31748f"
    markedBaseCommitBgColor:
      - "#f6c177"
    unstagedChangesColor:
      - "#eb6f92"
    defaultFgColor:
      - "#e0def4"
  authorColors:
    "*": "#c4a7e7"
