#!/bin/bash
# Рамка вокруг активного окна (Rosé Pine: iris → rose)
options=(
    style=round
    width=5.0
    hidpi=on
    active_color="gradient(top_left=0xffc4a7e7,bottom_right=0xffebbcba)"
    inactive_color=0x00000000
)
borders "${options[@]}"
